version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./web:/var/www/html"
      - "./nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    container_name: nginx
    environment:
    - NGINX_HOST=${NGINX_HOST}
    ports:
    - "8080:80"
    links:
      - php
  php:
    build: ./docker
    volumes:
    - "./web:/var/www/html"
    container_name: php
    links:
      - mysql
  mysql:
      image: mysql:5.7
      container_name: mysql
      env_file:
        - .env
      environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
      - "3306:3306"
      volumes:
      - "./data/db/mysql:/var/lib/mysql"